# To get started with Dependabot version updates, you'll need to specify which
# package ecosystems to update and where the package manifests are located.
# Please see the documentation for all configuration options:
# https://docs.github.com/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: develop
    allow:
      - dependency-name: "actions/checkout"
      - dependency-name: "astral-sh/setup-uv"
      - dependency-name: "actions/upload-artifact"
      - dependency-name: "actions/download-artifact"
      - dependency-name: "actions/cache"
      - dependency-name: "rtCamp/action-slack-notify"
      - dependency-name: "pypa/gh-action-pypi-publish"
      - dependency-name: "anthropics/claude-code-action"
      - dependency-name: "shiguredo/github-actions"
      - dependency-name: "tailscale/github-action"
      - dependency-name: "Homebrew/actions"
      - dependency-name: "actions/dependency-review-action"
  - package-ecosystem: uv
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: develop
